version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import

  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
    depends_on:
      - keycloak
